language: php

php:
  - 5.6

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo service memcached start

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml
